#!/bin/sh -Cu
# __ This sandbox is not fully sealed! Read the script before executing it. __
#
# DENY some /dev files.
# Webcam access denial, via `/dev/video[0-9]*`, may need more entries!
#
d_dev=/dev/snd:/dev/v4l:/dev/video0:/dev/video1:/dev/video2

# DENY package-manager files.
#
d_pkg=/etc/portage

# DENY sensitive files.
#
d_private=/boot:/mnt:${XDG_CONFIG_HOME}/tpm:${XDG_DOCUMENTS_DIR}

# DENY some /var files.
#
d_var=/var/db:/var/lib:/var/log:/var/spool

# WRITE cache files.
#
w_cache=${HOME}/.mozilla:${XDG_CACHE_HOME}/mozilla

# Write dbus request.
#
w_dbus=${XDG_RUNTIME_DIR}/bus-proxy/firefox

# WRITE download files.
#
w_dl=${XDG_DOWNLOAD_DIR}

# Write dri request.
#
w_dri=/dev/dri/renderD128

# WRITE process files.
# For this to be "secure", the PID namespace must be isolated!
#
w_proc=/proc

# WRITE temporary files.
#
w_tmpdir=${XDG_RUNTIME_DIR}/firefox

# Ensure PATHs in volatile directories exist.
#
mkdir -p ${XDG_RUNTIME_DIR}/bus-proxy
mkdir -p ${XDG_RUNTIME_DIR}/firefox

# Enhance sandbox by filtering dbus requests. Send to background.
#
xdg-dbus-proxy $DBUS_SESSION_BUS_ADDRESS $w_dbus			\
--filter								\
--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*		\
--call=org.freedesktop.portal.*=*					\
--own=org.mozilla.firefox.*						\
--talk=org.pipewire.node						\
&

export DBUS_SESSION_BUS_ADDRESS="unix:path=${w_dbus}"
export MOZ_ENABLE_WAYLAND=1
export SANDBOX_DENY=${d_dev}:${d_pkg}:${d_private}:${d_var}
export SANDBOX_WRITE=${w_cache}:${w_dbus}:${w_dl}:${w_dri}:${w_proc}:${w_tmpdir}
export TMPDIR=${w_tmpdir}

# Enhance sandbox by isolating namespaces. Hand over control to sandbox.
#
unshare -Ufimp --map-auto --mount-proc -- sandbox -- firefox $@

# Process has ended. Cleanup.
#
kill ${!}
