#!/bin/sh -aeu
# Limit Firefox using landlock-LSM backed sandbox.

# These environment variables *must* be defined:
#
# DBUS_SESSION_BUS_ADDRESS
# HOME
# WAYLAND_DISPLAY
# XDG_RUNTIME_DIR

# These environment variables *should* be defined:
#
# PIPEWIRE_CORE
# PIPEWIRE_RUNTIME_DIR
# XDG_CACHE_HOME
# XDG_DOWNLOAD_DIR
# XDG_PUBLICSHARE_DIR

# These guidelines *should* be followed:
#
# The proc-filesystem (i.e. /proc) is mounted with `hidepid=ptraceable` option.
# The user is not in the `video` group.
# The user reads the entire script.

# A seperate temporary directory significantly decreases runtime attack-surface.
rundir="${XDG_RUNTIME_DIR}/landlock/firefox-${$}"
mkdir -p "$rundir"

# A dbus-proxy significantly decreases runtime attack-surface.
dbus_proxy="${rundir}/bus"
xdg-dbus-proxy "$DBUS_SESSION_BUS_ADDRESS" "$dbus_proxy"	\
--filter							\
--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*	\
--call=org.freedesktop.portal.*=*				\
--own=org.mozilla.firefox.*					\
--own=org.mpris.MediaPlayer2.firefox.*				\
&

# Hack (TODO: find a better way to ensure proxy is up)
sleep 1
DBUS_SESSION_BUS_ADDRESS="unix:path=${dbus_proxy}"

# PIPEWIRE_* uses standard-default as a fallback.
PIPEWIRE_CORE="${PIPEWIRE_CORE:-pipewire-0}"
PIPEWIRE_RUNTIME_DIR="${PIPEWIRE_RUNTIME_DIR:-$XDG_RUNTIME_DIR}"

# Firefox creates a wayland-proxy using $WAYLAND_DISPLAY. To avoid having to
# read-write the entire $XDG_RUNTIME_DIR, use a read-only"able" absolute-path.
WAYLAND_DISPLAY="${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}"

# XDG_* uses standard-default as a fallback.
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_DOWNLOAD_DIR="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}"
XDG_PUBLICSHARE_DIR="${XDG_PUBLICSHARE_DIR:-$HOME/Public}"

# Read-only PATHs
LL_FS_RO="/bin/basename:/bin/bash:/bin/dirname:/bin/expr:/bin/firefox:/bin/killall:/bin/pwd:/bin/tr:/bin/uname:/bin/which:/etc/fonts:/etc/gtk-3.0:/etc/hosts:/etc/ld-musl-x86_64.path:/etc/mime.types:/etc/os-release:/etc/resolv.conf:/etc/ssl/certs/ca-certificates.crt:/lib:/sys/bus:/sys/class:/sys/devices:/usr/include:/usr/lib:/usr/share:${XDG_PUBLICSHARE_DIR}"

# Read-write PATHs
LL_FS_RW="/dev:/proc:${HOME}/.mozilla:${XDG_CACHE_HOME}/mozilla:${PIPEWIRE_RUNTIME_DIR}/${PIPEWIRE_CORE}:${WAYLAND_DISPLAY}:${XDG_DOWNLOAD_DIR}:${dbus_proxy}:${rundir}"

# Bindable ports (for server programs)
LL_TCP_BIND=""

# Connectable ports (for client programs)
LL_TCP_CONNECT="80:443"

# These environment variables are intentionally set after LL_* .
TMPDIR="$rundir"
XDG_RUNTIME_DIR="$rundir"

# Prevent leakage to limit side-channel attacks.
unset dbus_proxy
unset rundir

sandboxer firefox "$@"

# Cleanup resources.
kill ${!}
rm -r $XDG_RUNTIME_DIR
