#!/bin/sh -Ceu
# __ This sandbox is not fully sealed! Read the script before executing it. __
#
# DENY some /dev files.
# Webcam access denial, via `/dev/video[0-9]*`, may need more entries.
#
deny_dev=/dev/snd:/dev/v4l:/dev/video0:/dev/video1:/dev/video2

# DENY package-manager files.
#
deny_pkg=/etc/portage

# DENY sensitive files.
#
deny_private=/boot:/mnt:${XDG_CONFIG_HOME}/tpm:${XDG_DOCUMENTS_DIR}

# DENY some /var files.
#
deny_var=/var/db:/var/lib:/var/log:/var/spool

# WRITE cache files.
#
write_cache=${HOME}/.mozilla:${XDG_CACHE_HOME}/mozilla

# Write dbus request.
#
write_dbus=${XDG_RUNTIME_DIR}/bus-proxy/firefox

# WRITE download files.
#
write_dl=${XDG_DOWNLOAD_DIR}

# WRITE temporary files.
#
write_tmpdir=${XDG_RUNTIME_DIR}/firefox

export SANDBOX_DENY=${deny_dev}:${deny_pkg}:${deny_private}:${deny_var}
export SANDBOX_WRITE=${write_cache}:${write_dbus}:${write_dl}:${write_tmpdir}
export TMPDIR=${write_tmpdir}

# Enhance sandbox by filtering dbus requests. Send to background.
#
xdg-dbus-proxy $DBUS_SESSION_BUS_ADDRESS $write_dbus			\
--filter								\
--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*		\
--call=org.freedesktop.portal.*=*					\
--own=org.mozilla.firefox.*						\
--talk=ca.desrt.dconf							\
--talk=org.pipewire.node						\
&

# Set xdg-dbus-proxy as the main dbus.
#
export DBUS_SESSION_BUS_ADDRESS=${write_dbus}

# Hand over control to sandbox.
#
exec sandbox -- firefox $@
