#!/bin/sh -Ceu
# __ This sandbox is not fully sealed! Read the script before executing it. __
#
# DENY some /dev files.
# Webcam access denial, via `/dev/video[0-9]*`, may need more entries.
#
deny_dev=/dev/snd:/dev/v4l:/dev/video0:/dev/video1:/dev/video2

# DENY package-manager files.
#
deny_pkg=/etc/portage

# DENY sensitive files.
#
deny_private=/boot:/mnt:${XDG_CONFIG_HOME}/tpm:${XDG_DOCUMENTS_DIR}

# DENY some /var files.
#
deny_var=/var/db:/var/lib:/var/log:/var/spool

# WRITE cache files.
#
write_cache=${HOME}/.mozilla:${XDG_CACHE_HOME}/mozilla

# Write dbus request.
#
write_dbus=${XDG_RUNTIME_DIR}/bus-proxy/firefox

# WRITE download files.
#
write_dl=${XDG_DOWNLOAD_DIR}

# WRITE temporary files.
#
write_tmpdir=${XDG_RUNTIME_DIR}/firefox

export NAMESPACE_IPC_ENABLE=yes
export NAMESPACE_MNT_ENABLE=yes
export NAMESPACE_PID_ENABLE=yes
export SANDBOX_DENY=${deny_dev}:${deny_pkg}:${deny_private}:${deny_var}
export SANDBOX_WRITE=${write_cache}:${write_dbus}:${write_dl}:${write_tmpdir}
export TMPDIR=${write_tmpdir}

# Prepare file-descriptor for notifications.
#
mkdir -p $TMPDIR

fd_num=8
fd_path=${TMPDIR}/notify.${$}

mkfifo -m 600 $fd_path
exec ${fd_num}<> $fd_path

# Enhance sandbox by filtering dbus requests. Send to background.
#
xdg-dbus-proxy --fd=${fd_num} $DBUS_SESSION_BUS_ADDRESS $write_dbus	\
--filter								\
--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*		\
--call=org.freedesktop.portal.*=*					\
--own=org.mozilla.firefox.*						\
--talk=ca.desrt.dconf							\
--talk=org.pipewire.node						\
&

# Block until xdg-dbus-proxy is ready.
#
# MUST FIX; detects notification but fails, as expected, which ends the script.
# This is not a solution to strive for. Its wacky, hacky, and likely buggy.
#
xargs -0 -s5 -x <${fd_num}

# Set xdg-dbus-proxy as the main dbus.
#
export DBUS_SESSION_BUS_ADDRESS=${write_dbus}

# Everything is in order, cleanup to minimize attack-surface.
#
exec ${fd_num}>&-
rm $fd_path

# Hand over control to sandbox.
#
exec sandbox -- firefox $@
