#!/usr/bin/env sh
# Strip (U)EFI syntax from efibootdump.
# A few notes:
#
#	A) The functionality of this script can be replaced with `efibootmgr -u`
#	and `awk`, if efivarfs is accessible and boot-entry is present.
#
#	B) This is intended for efi boot-entry arguments and may mangle certain
#	values if piped directly from `efibootdump` (i.e. \vm.efi -> \vmefi).
#
#	C) '-E' is POSIX compliant, but if your system does not support it, use
#	'\(' instead of '(' in the expressions.
#
#	D) The first expression adds whitespace (i.e. char..char -> char char).
#
#	E) The second expression removes the '.' delimiter (i.e. char. -> char).
#
exec /bin/sed -E				\
	-e 's/([^\.])\.\.([^\.])/\1 \2/g'	\
	-e 's/([[:print:]])\./\1/g'		\
"$@"
